version: '3.8'

services:
  db:
    image: postgres:15
    container_name: estocafy_db
    restart: always
    environment:
      POSTGRES_DB: estocafy
      POSTGRES_USER: estocafy
      POSTGRES_PASSWORD: estocafy123
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estocafy_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/estocafy
      SPRING_DATASOURCE_USERNAME: estocafy
      SPRING_DATASOURCE_PASSWORD: estocafy123
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
