server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estocafy
    username: estocafy
    password: estocafy123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    com.estocafy: DEBUG
