server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estocafy
    username: estocafy
    password: estocafy123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: localhost
    port: 5672
    username: estocafy
    password: estocafy123
    virtual-host: /
  
  sendgrid:
    api-key: SENDGRID_API_KEY
  
  notification:
    expiry-days: 7
  
  scheduler:
    enabled: true
    daily-check-cron: 0 0 6 * * *

logging:
  level:
    org.springframework: INFO
    com.estocafy: DEBUG
